"use client";

import { useState } from "react";
import styles from "./page.module.css";

type Section = { title: string; paragraphs?: string[]; groups?: { label: string; items: string[] }[]; bullets?: string[] };

const minorPolicy: Section[] = [
  { title: "1. Purpose of This Policy", paragraphs: ["ShiftSupport engages minors (ages 14–17) for flexible, part-time work opportunities.", "This policy ensures that all minor workers are hired, scheduled, and supervised in compliance with California labor laws and applicable federal regulations."] },
  { title: "2. Eligibility to Work at ShiftSupport", paragraphs: ["ShiftSupport hires minors who meet the following criteria:"], bullets: ["Ages 14–15: Eligible for non-hazardous, part-time work with strict hour limits.", "Ages 16–17: Eligible for non-hazardous work with expanded scheduling flexibility.", "Under 14: Not eligible for ShiftSupport work."] },
  { title: "3. Required Documentation", paragraphs: ["Before a minor can begin working, ShiftSupport must receive the required documentation."], groups: [{ label: "Work Permit", items: ["“Permit to Employ and Work” issued by the minor’s school district.", "Signed by the school, parent/guardian, and employer.", "Must be renewed each school year and each summer."] }, { label: "Parental/Guardian Consent", items: ["Signed Parental Consent for Background Check.", "Signed Parental Consent to Work with ShiftSupport.", "Parent/guardian emergency contact information."] }, { label: "Identity Verification", items: ["Government-issued ID, state ID, school ID, or passport as applicable.", "Required payroll/employment identity information."] }] },
  { title: "4. Background Check Policy for Minors", paragraphs: ["ShiftSupport conducts only legally permitted screening for minors.", "ShiftSupport does not access sealed juvenile criminal records where those records are legally unavailable.", "A parent or legal guardian must authorize any required background check."], bullets: ["Identity verification", "SSN trace", "Sex Offender Registry search", "Global watchlist search"] },
  { title: "5. Allowed Work Hours", paragraphs: ["ShiftSupport follows applicable California minor work-hour requirements. This information describes ShiftSupport policy and is not legal advice."], groups: [{ label: "Ages 14–15", items: ["School days: Up to 3 hours", "Non-school days: Up to 8 hours", "Weekly maximum: 18 hours during school weeks", "Work hours: 7 a.m.–7 p.m., with applicable seasonal extensions where legally permitted"] }, { label: "Ages 16–17", items: ["School days: Up to 4 hours", "Non-school days: Up to 8 hours", "Weekly maximum: Up to applicable California limits", "Work hours must comply with California school-day and non-school-day restrictions"] }] },
  { title: "6. Prohibited Work for Minors", paragraphs: ["ShiftSupport does not assign minors to hazardous or restricted tasks, including:", "Minors are assigned only to safe, supervised, non-hazardous tasks permitted under applicable law."], bullets: ["Driving motor vehicles", "Operating prohibited power-driven machinery", "Working at prohibited heights", "Handling restricted heavy equipment", "Working with hazardous chemicals/materials", "Security, enforcement, or safety-critical roles"] },
  { title: "7. Supervision & Safety Requirements", paragraphs: ["ShiftSupport requires:"], bullets: ["Appropriate adult supervision", "Accessible emergency contact information", "Task-appropriate safety instructions", "Safe working environments", "Access to ShiftSupport support during applicable shifts"] },
  { title: "8. Communication With Parents/Guardians", paragraphs: ["Where required/applicable, ShiftSupport maintains appropriate communication with parents or guardians regarding:"], bullets: ["Hiring", "Required documents", "Shift information", "Emergency notifications", "Relevant policy updates"] },
  { title: "9. Zero-Tolerance Policies", paragraphs: ["ShiftSupport prohibits:", "Violations may result in removal or account action."], bullets: ["Harassment or discrimination", "Unsafe behavior", "Working outside permitted hours", "Misrepresentation of age or identity", "Assigning minors prohibited tasks"] },
  { title: "10. Policy Updates", paragraphs: ["ShiftSupport reviews this policy periodically to maintain alignment with applicable California and federal requirements."] },
];

const conduct: Section[] = [
  { title: "1. Introduction", paragraphs: ["Welcome to ShiftSupport.", "We connect local helpers with local shops for short, flexible shifts.", "This rule book explains how to work safely, respectfully, and professionally while representing ShiftSupport.", "Our goals:"], bullets: ["Support local retailers", "Provide quick, reliable help", "Create positive experiences for everyone involved"] },
  { title: "2. General Expectations", groups: [{ label: "Be Reliable", items: ["Arrive on time.", "5–10 minutes early is recommended where practical.", "If you are running late, communicate promptly.", "Never abandon a shift early without approval."] }, { label: "Be Professional", items: ["Be polite, friendly, and attentive.", "Avoid unnecessary phone use while working.", "Follow instructions and ask questions when unsure."] }, { label: "Be Safe", items: ["Use proper lifting techniques.", "Do not operate equipment unless authorized and appropriately trained.", "Report unsafe conditions immediately."] }, { label: "Be Honest", items: ["Log hours accurately.", "Do not claim work you did not perform.", "Follow ShiftSupport payment and workplace rules."] }] },
  { title: "3. Appearance & Conduct", groups: [{ label: "Dress Code", items: ["Wear clean, neat clothing.", "Closed-toe shoes where required.", "Follow any shift-specific dress requirements."] }, { label: "Behavior", items: ["No harassment, discrimination, threats, or aggressive behavior.", "Maintain professional behavior around customers.", "Drugs and alcohol are prohibited before or during shifts."] }] },
  { title: "4. Communication", groups: [{ label: "With Retailers", items: ["Introduce yourself upon arrival.", "Confirm tasks before beginning.", "Notify the retailer when tasks are complete.", "Ask for clarification rather than guessing."] }, { label: "Contact ShiftSupport When", items: ["You are running late", "A task appears unsafe", "There is a workplace conflict", "A retailer requests work outside the agreed scope", "You cannot complete the shift"] }] },
  { title: "5. Shift Procedures", groups: [{ label: "Before", items: ["Review shift details", "Confirm location and timing", "Prepare required clothing/equipment"] }, { label: "During", items: ["Follow approved instructions", "Stay within the agreed task scope", "Remain available and professional"] }, { label: "After", items: ["Confirm completion", "Clean your work area", "Log/confirm worked hours through the applicable ShiftSupport process", "Leave after the shift is properly completed"] }] },
  { title: "6. Task Restrictions", paragraphs: ["Workers must not perform restricted or unsafe work unless explicitly permitted by ShiftSupport and applicable law. Examples include:"], bullets: ["Prohibited industrial machinery", "Unsafe ladder work", "Electrical/plumbing work", "Hazardous chemicals/materials", "Restricted warehouse areas", "Unsafe lifting beyond approved task requirements"] },
  { title: "7. Safety Rules", bullets: ["Keep walkways clear", "Use appropriate protective equipment", "Lift safely", "Report injuries promptly", "Stop and report work that appears unsafe"] },
  { title: "8. Payments", paragraphs: ["Workers are paid through ShiftSupport according to the applicable payroll process and pay schedule.", "Workers should accurately confirm worked hours and follow the platform’s payment procedures.", "Do not accept or arrange off-platform payment for ShiftSupport shifts unless expressly permitted by ShiftSupport policy."] },
  { title: "9. Cancellations", paragraphs: ["Workers should follow the applicable ShiftSupport cancellation policy and provide as much notice as possible if they cannot attend a confirmed shift.", "Repeated late cancellations or no-shows may result in account restrictions.", "Retailer cancellations are handled according to the applicable ShiftSupport cancellation policy."] },
  { title: "10. Confidentiality", paragraphs: ["Workers must protect retailer information. Do not:"], bullets: ["Take unauthorized photos", "Publish private shift information", "Share confidential store/business operations"] },
  { title: "11. Violations & Consequences", paragraphs: ["ShiftSupport may issue warnings, restrictions, suspension, or removal for serious or repeated violations including:"], bullets: ["Repeated lateness", "Misconduct", "Fraudulent hours", "Ignoring safety requirements", "Harassment or discrimination"] },
  { title: "12. Appreciation", paragraphs: ["ShiftSupport values the time and effort of its workers.", "Your work helps local businesses stay supported while giving you a flexible way to earn.", "Thank you for being part of the ShiftSupport community."] },
];

const documents = [
  ["Worker & Parent Agreement", "Review the worker and parent/guardian agreement for applicable ShiftSupport participation.", "View Agreement", "https://cdn.prod.website-files.com/6968056bfb2385986ec61801/6a024f5c34394c8f248b449c_worker%20parent%20agreement.pdf"],
  ["School Counselor Document", "Information for schools and counselors supporting eligible student workers.", "View School Document", "https://cdn.prod.website-files.com/6968056bfb2385986ec61801/6a03557d0cfc4f59e5b7a518_school%20counselor%20document.pdf"],
  ["Retailer Responsibilities", "Review workplace responsibilities for retailers working with ShiftSupport workers.", "View Retailer Responsibilities", "https://cdn.prod.website-files.com/6968056bfb2385986ec61801/6a0357d959187b63a52bc0e1_retailer%20responsibilities.pdf"],
];

function Policy({ title, subtitle, sections }: { title: string; subtitle: string; sections: Section[] }) {
  return <div className={styles.policyPanel}><header className={styles.resourceHeader}><span className={`headingFont ${styles.resourceTag}`}>WORKER POLICY</span><h3>{title}</h3><p>{subtitle}</p></header><div className={styles.policyContent}>{sections.map(section => <section className={styles.policySection} key={section.title}><h4>{section.title}</h4>{section.paragraphs?.map(p => <p key={p}>{p}</p>)}{section.bullets && <ul>{section.bullets.map(item => <li key={item}>{item}</li>)}</ul>}{section.groups?.map(group => <div className={styles.policyGroup} key={group.label}><h5>{group.label}</h5><ul>{group.items.map(item => <li key={item}>{item}</li>)}</ul></div>)}</section>)}</div></div>;
}

function DocIcon() { return <span className={styles.docIcon} aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6"><path d="M7 3.5h7L18.5 8v12.5H7zM13.5 3.5V8h5M9.5 12h6M9.5 15h6" /></svg></span>; }

export default function WorkerResources() {
  const [active, setActive] = useState(0);
  const tabs = ["Minor Policy", "Code of Conduct", "Permit Documents"];
  return <section className={styles.resourcesSection}><div className="container"><div className={styles.resourcesHeading}><p className={`headingFont ${styles.eyebrow}`}><span aria-hidden="true" />WORKER RESOURCES</p><h2>Policies, Safety &amp; Required Documents.</h2><p>Review the policies and documents that help keep every ShiftSupport opportunity safe, clear, and compliant.</p></div><div className={styles.tabs} role="tablist" aria-label="Worker resources">{tabs.map((tab,index)=><button type="button" role="tab" id={`worker-tab-${index}`} aria-selected={active===index} aria-controls={`worker-panel-${index}`} className={`${styles.tabButton} ${active===index?styles.activeTab:""}`} onClick={()=>setActive(index)} key={tab}>{tab}</button>)}</div><div className={styles.tabContent} role="tabpanel" id={`worker-panel-${active}`} aria-labelledby={`worker-tab-${active}`}>
    {active===0&&<Policy title="ShiftSupport Minor Hiring & Safety Policy" subtitle="California-Compliant — Applies to Workers Under 18" sections={minorPolicy}/>} 
    {active===1&&<Policy title={"ShiftSupport – Worker Rule Book\n2026 Edition"} subtitle="A simple guide for helpers working short shifts through the ShiftSupport platform." sections={conduct}/>} 
    {active===2&&<div className={styles.documentsPanel}><header><span className={`headingFont ${styles.resourceTag}`}>PDF RESOURCES</span><h3>Worker &amp; Minor Employment Documents</h3><p>Access the documents that may be required for workers, parents/guardians, schools, and participating businesses.</p></header><div className={styles.documentGrid}>{documents.map(([title,description,button,href])=><article className={styles.documentCard} key={title}><DocIcon/><h4>{title}</h4><p>{description}</p><a href={href} target="_blank" rel="noreferrer">{button} <span aria-hidden="true">↗</span></a></article>)}</div></div>}
  </div></div></section>;
}
